services:

  # Tu API de FastAPI
  backend:
    build: ./backend
    container_name: sut-backend
    ports:
      - "8001:8000"
    volumes:
      # Esto evita que pierdas tus datos si borrás el contenedor
      - ./backend:/code
    environment:
      - DATABASE_URL=sqlite:////code/qa_automation.db

  frontend:
    build: ./frontend-qa
    container_name: sut-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
