services:


  # Tu API de FastAPI
  backend:
    build: ./backend
    container_name: sut-backend
    ports:
      - "8000:8000"
    volumes:
      # Esto evita que pierdas tus datos si borrás el contenedor
      - ./backend/qa_automation.db:/code/qa_automation.db
    environment:
      - DATABASE_URL=sqlite:///./qa_automation.db

  frontend:
    build: ./frontend-qa
    container_name: sut-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

